# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '链式、函数式、响应式编程' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 链式、函数式、响应式编程
  
  pod'ReactiveObjC'

  target '链式、函数式、响应式编程Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '链式、函数式、响应式编程UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
